### ISSUE TITLE
Account Class

### ISSUE THREAD

**Issue by Vineet77** [SIGBlockchain/project_red#19]
Since Java is an object oriented language, all data will be encapsulated in classes/objects. The first class we will make is the `Account` class. You will be working on the branch [account_info](https://github.com/SIGBlockchain/project_red/tree/account_info)

The Account class will have the following fields: 
* `WalletAddress` (String)
* `Balance` (unsigned 64 bit integer)
* `StateNonce` (unsigned 64 bit integer)

The `Account` class should have two constructors.
* One that only takes in a Wallet Address 
* One that takes in a Wallet Address, Balance and StateNonce. 

The Wallet Address Field should have a getter function (but not a setter). 
The Balance and StateNonce should have both setters and getters. 

The class will be in the Account.java file in the package `sigblockchain.projectred.client` in the module `client`.  [ package `sigblockchain.projectred.client` in the module `client`.](https://github.com/SIGBlockchain/project_red/blob/account_info/client/src/main/java/sigblockchain/projectred/client/Account.java)

You will also implement unit tests (using [JUnit] (https://junit.org/junit5/docs/current/user-guide/))for each constructor, getter and setter. The test will be in the test source directory in the  [corresponding package](https://github.com/SIGBlockchain/project_red/tree/account_info/client/src/test/java/sigblockchain/projectred/client).

**Comment by pradiptikayal** [comment]
I would like to work on this issue.

**Comment by pradiptikayal** [comment]
I have a pull request ready, please give me permission, to create pull request.

**Comment by dhodcz2** [comment]
I was going to work on this Sunday. I was assigned it and I'm the newcomer
here so it would be a good introduction.

**Comment by pradiptikayal** [comment]
Okay sure. Go ahead. All the best. Feel free to ask, if you face any issues.

**Comment by Vineet77** [comment]
Hi @pradiptikayal, I'm really glad that you're eager to contribute. I'll add you to the organization. Typically we self-assign issues at the meeting, so I didn't know you were interested in one. I'll create more issues soon. Is there a way I can get in contact with you?

**Comment by pradiptikayal** [comment]
Hi @Vineet77 , you can contact me via linkedIn
https://www.linkedin.com/in/pradipti-kayal/

**Comment by dhodcz2** [comment]
I won't be able to finish this today but I can work on it Tuesday. Is that too late?

**Comment by Vineet77** [comment]
Tuesday is fine, but please try to finish it by Wednesday, because we need this to be done to move on to other things. If you have any trouble, don't be afraid to contact me.

**Comment by dhodcz2** [comment]
I have committed my code via the IntelliJ GUI. Please let me know if everything checks out.

**Comment by Vineet77** [comment]
Closed by https://github.com/SIGBlockchain/project_red/pull/29
