### ISSUE TITLE
Info Fields

### ISSUE THREAD

**Issue by ramirez915** [SIGBlockchain/project_red#7]
Where: **InfoRow**

Create TextFields and Labels that correspond to the following: **Aurum Wallet**, **Balance**, **State Nonce**, and **Message from Producer**. These will be used to display user information.
Put Labels on **first row** then TextFields in the **row below**.

- [x] Aurum Wallet Field + Label

- [x] Balance Field + Label

- [x] State Nonce Field + Label

- [x] Message from Producer Field + Label

- [x] All placed in grid

- [ ] Successfully displayed

Additional sources:
Look at the grid box example to get an idea of how to use
https://blog.idrsolutions.com/2015/07/an-introduction-to-javafx-panes-with-code-examples/
https://www.tutorialspoint.com/javafx/layout_gridpane.htm

Refer to this visual

<img width="873" alt="aurumGui" src="https://user-images.githubusercontent.com/43687517/66719791-d16fab80-edb9-11e9-883b-05d774f4ae47.PNG">

**Comment by bashbashbash** [comment]
PR #12

**Comment by bashbashbash** [comment]
Complete
