### ISSUE TITLE
Send Aurum Fields

### ISSUE THREAD

**Issue by ramirez915** [SIGBlockchain/project_red#8]
Where: **SendAurumRow**

Create the TextFields and Labels that will be used when users want to send Aurum to another user. **Send To** and **Amount** Labels with their TextField and the **Send** Button. Put Fields, Labels and Button into the grid. Preferably in the third row right below the row containing the user information TextFields.

A Label is **not** needed for the Send Button. Text can be placed in the Button through its constructor.

- [x] Send To TextField + Label

- [x] Amount TextField + Label

- [x] Send Button

- [x] All placed on grid

- [x] Successfully displayed

Additional sources:
Look at the grid box example to get an idea of how to use
https://blog.idrsolutions.com/2015/07/an-introduction-to-javafx-panes-with-code-examples/
https://www.tutorialspoint.com/javafx/layout_gridpane.htm

Refer to visual

<img width="873" alt="aurumGui" src="https://user-images.githubusercontent.com/43687517/66720015-cd915880-edbc-11e9-9d50-b86d9a82b897.PNG">

**Comment by harshalpatel165** [comment]
Where exactly am i writing the code for this in the project red folder

**Comment by ramirez915** [comment]
Good job! Looks good. Might need to modify a little when merging everything else but shouldn't be too much to modify

**Comment by harshalpatel165** [comment]
completed
