### ISSUE TITLE
Update Button

### ISSUE THREAD

**Issue by ramirez915** [SIGBlockchain/project_red#9]
Where: **MiscRow**

We need a Button to update user wallet. Create **Update** Button and add to the grid. Preferably in the row with the Info fields. If there seems to be a better place for this Button place it wherever it seems better to go.

**No** label is needed for the button. The Button constructor takes in a string that is used to put text on the Button.

- [x] Button is created

- [x] Placed in the grid

- [x] Successfully displayed when running main

Additional sources:
Look at the grid box example to get an idea of how to use
https://blog.idrsolutions.com/2015/07/an-introduction-to-javafx-panes-with-code-examples/
https://www.tutorialspoint.com/javafx/layout_gridpane.htm

Refer to visual

<img width="873" alt="aurumGui" src="https://user-images.githubusercontent.com/43687517/66720059-5d370700-edbd-11e9-902e-740211a93608.PNG">

**Comment by HarryL5004** [comment]
How should I compile and test the java files? I keep getting this error: `Error: Could not find or load main class `

**Comment by HarryL5004** [comment]
Completed
